# GNUPLOT file generated by OpenCalphad
# OpenCalphad   6.119 :  2026-06-10 : with GNUPLOT
# subroutine ocplot2B
set terminal wxt size 840,700 font "Arial,16"
#set terminal pdf color solid size 6,5 enhanced font "Arial,16"
#set output "ocgnu.pdf"
set title "OpenCalphad   6.119 :  2026-06-10 : with GNUPLOT \n P=101325, N=1, X(TI)=0.1, T=X," font "Arial,10" 
set origin 0.0, 0.0 
set size   1.0000,   1.0000
set xlabel "T"
set ylabel "NP(*)"
set label "~O{.0  C}" at screen 0.02, 0.03 font "Baskerville,20"
set key top right font "Arial,12"
set style line  1 lt  1 lc rgb "#000000" lw 2 pt 10
set style line  2 lt  1 lc rgb "#4169E1" lw 2 pt 6
set style line  3 lt  1 lc rgb "#00C000" lw 2 pt 3
set style line  4 lt  1 lc rgb "#FF0000" lw 2 pt 2
set style line  5 lt  1 lc rgb "#FF00FF" lw 2 pt 4
set style line  6 lt  1 lc rgb "#C8C800" lw 2 pt 5
set style line  7 lt  1 lc rgb "#C0C0C0" lw 2 pt 7
set style line  8 lt  1 lc rgb "#00FFFF" lw 2 pt 8
set style line  9 lt  1 lc rgb "#804080" lw 2 pt 9
set style line 10 lt  1 lc rgb "#7CFF40" lw 2 pt 1
# for invariants, faded read
set style line 100 lt 1 lc rgb "#FF3333" lw 3 pt 1

# Some useful GNUPLOT commands for editing the figure
# ** THIS IS A DASHED LINE (on pdf/wxt):
# set style line 15 lt 0 lc rgb "#C8C800" lw 2 pt 2

# set pointsize 0.6
# set label "text" at 0.5, 0.5 rotate by 60 font "arial,12"
# set xrange [0.5 : 0.7] 
# ** ADDING MANUALLY A LINE AND KEEP SCALING:
# set arrow from x0, y0 to x1,y1 nohead linestyle 1
# ** ADD A RED DOT AT 0.1,1000:
# set obj 1 circle fc rgb "#FF0000" fs sol size 0.02 noclip at 1,1
# ** MODIFY THE PLOTTED VALUE ON AN AXIS:
# plot for [i=] ... using (2*column(i)/(1-2*column(i))):2 with ...
# ** PLOTTING SYMBOLS INSTEAD OF LINE:
# ... using 2:i with points pt 7 ps 3 
# ** OVERLAY PLOTS: 
# set multiplot
# set xrange [] writeback
#  ... plot someting
# set xrange restore
#  ... plot more using same axis scaling 
# unset multiplot



# begin of data with lines     33
$OCT260610225030 << EOD
KEYS:  T NP(ETA) NP(FCC-A1) 
 # First line: ETA FCC_A1
   1    1.000000E+03    2.042811E-01    7.957189E-01
# shift of line   1


   2    1.000000E+03    2.042811E-01    7.957189E-01
   3    9.999900E+02    2.042858E-01    7.957142E-01
   4    9.999800E+02    2.042905E-01    7.957095E-01
   5    9.979800E+02    2.052308E-01    7.947692E-01
   6    9.959800E+02    2.061669E-01    7.938331E-01
   7    9.939800E+02    2.070988E-01    7.929012E-01
   8    9.900000E+02    2.089409E-01    7.910591E-01
   9    9.800000E+02    2.134983E-01    7.865017E-01
  10    9.700000E+02    2.179576E-01    7.820424E-01
  11    9.600000E+02    2.223227E-01    7.776773E-01
  12    9.500000E+02    2.265974E-01    7.734026E-01
  13    9.400000E+02    2.307855E-01    7.692145E-01
  14    9.300000E+02    2.348903E-01    7.651097E-01
  15    9.200000E+02    2.389152E-01    7.610848E-01
  16    9.100000E+02    2.428635E-01    7.571365E-01
  17    9.000000E+02    2.467382E-01    7.532618E-01
  18    8.900000E+02    2.505423E-01    7.494577E-01
  19    8.800000E+02    2.542788E-01    7.457212E-01
  20    8.700000E+02    2.579504E-01    7.420496E-01
  21    8.600000E+02    2.615598E-01    7.384402E-01
  22    8.500000E+02    2.651097E-01    7.348903E-01
  23    8.400000E+02    2.686027E-01    7.313973E-01
  24    8.300000E+02    2.720414E-01    7.279586E-01
  25    8.200000E+02    2.754283E-01    7.245717E-01
  26    8.100000E+02    2.787659E-01    7.212341E-01
  27    8.000000E+02    2.820567E-01    7.179433E-01
  28    7.900000E+02    2.853032E-01    7.146968E-01
  29    7.800000E+02    2.885079E-01    7.114921E-01
  30    7.700000E+02    2.916733E-01    7.083267E-01
  31    7.600000E+02    2.948021E-01    7.051979E-01
  32    7.500000E+02    2.978969E-01    7.021031E-01
  33    7.400000E+02    3.009605E-01    6.990395E-01
# end of line   2


EOD


plot for [i=3: 4] $OCT260610225030 using 2:i with lines ls (i-2+ 0) title columnheader(i)
pause mouse
